feat(excel): add sheet addressing
adobe/helix-data-embed pull request #162
Opened 2020-08-26 08:51 UTC by tripodsan

fixes #118

BREAKING CHANGE: the first sheet of an excel workbook is no longer
  returned by default, nor is the first table.
  Only sheets with the `helix-` prefix can be returned by data-embed.
  The sheet can be selected with the `sheet` request parameter,
  which defaults to `defaul`. i.e. If nothing specified, the sheet
  with the name `helix-default` is returned.
  By default the _used ranged_ of the selected sheet is returned.
  A table can be addressed usinf the `table` request parameter,
  which can be a table name or an index. For example, `table=Table1`
  will return the table with the name `Table1`, `table=1` will return
  the second table in the sheet. Note that specifying a table index
  will result in an additional request to lookup the table names.

2020-08-26 09:35 UTC, trieloff requested changes
If we have to break compatibility, let's make sure we update Google and Excel at the same time.

Overall, I'd much prefer a non-breaking change.

2020-08-26 09:45 UTC, tripodsan commented
> If we have to break compatibility, let's make sure we update Google and Excel at the same time.

ok.

> Overall, I'd much prefer a non-breaking change.

yes, we could serve the first sheet, if there is no helix-default. but this is one of the security problems we want to fix.
otherwise, you can expose any excel workbook, even the ones not meant for web.

2020-08-26 09:54 UTC, trieloff commented
> yes, we could serve the first sheet, if there is no helix-default. but this is one of the security problems we want to fix.
otherwise, you can expose any excel workbook, even the ones not meant for web.

A more gentle change would be to use the new behavior whenever there is a sheet called `helix-*` and serve the first sheet otherwise.

2020-08-26 09:58 UTC, tripodsan commented
> > yes, we could serve the first sheet, if there is no helix-default. but this is one of the security problems we want to fix.
> > otherwise, you can expose any excel workbook, even the ones not meant for web.
> 
> A more gentle change would be to use the new behavior whenever there is a sheet called `helix-*` and serve the first sheet otherwise.

exactly not. otherwise you can expose any excel sheet that does **not** have an `helix-*` sheet in it.

2020-08-26 10:01 UTC, trieloff commented
You can only expose the first sheet. I wouldn't allow the `table` parameter at all. And this only applies to workbooks that have been shared with Helix in the first place, so I don't see how this would result in additional disclosure.

2020-08-26 12:26 UTC, tripodsan commented
> You can only expose the first sheet.

currently, yes. you can only expose the first sheet.
with this enhancement, you can also expose other sheets. as requested in the issue.

> I wouldn't allow the `table` parameter at all. 

that would be another breaking change. in case someone really wants to share a specific table in a sheet, I think this is useful.

> And this only applies to workbooks that have been shared with Helix in the first place, so I don't see how this would result in additional disclosure.

yes - but, people have all sorts of workbooks in their drive that they might expose accidentally. so better safe than sorry.

2020-08-27 05:41 UTC, tripodsan commented
> A more gentle change would be to use the new behavior whenever there is a sheet called `helix-*` and serve the first sheet otherwise.

After discussion with @davidnuescheler we decided to go with this idea.

2020-08-27 09:54 UTC, trieloff approved these changes

2020-08-27 09:54 UTC, trieloff commented on README.md
> +- By default, the _used ranged_ of the selected sheet is returned.
```suggestion
- By default, the _used range_ of the selected sheet is returned.
```

2020-08-27 10:16 UTC, merged

2020-08-27 10:21 UTC, trieloff commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- `v1.9.0`
- [GitHub release](https://github.com/adobe/helix-data-embed/releases/tag/v1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: