feat: force http1 when invoking other runtime actions
adobe/helix-data-embed pull request #223
Opened 2020-12-04 16:13 UTC by stefan-guggisberg

The upcoming/new I/O Runtime environment is Azure-based and supports HTTP/2. This might lead to
issues with long-lived HTTP/2 sessions.

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

2020-12-04 20:15 UTC, trieloff approved these changes

2020-12-05 04:57 UTC, tripodsan requested changes

2020-12-05 04:57 UTC, tripodsan commented on src/matchers/run-query.js
> +});
I would add the `if (process.env.HELIX_FETCH_FORCE_HTTP1) {` like in all other actions.

2020-12-06 01:11 UTC, tripodsan approved these changes

2020-12-06 14:33 UTC, merged

2020-12-06 14:35 UTC, trieloff commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- `v2.1.0`
- [GitHub release](https://github.com/adobe/helix-data-embed/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: